// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.0
// source: routes.proto

package routes

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RoutesClient is the client API for Routes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoutesClient interface {
	// USER ROUTES //
	GetUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	DeleteUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	// WORKOUT ROUTES //
	GetWorkouts(ctx context.Context, in *User, opts ...grpc.CallOption) (*MultiWorkout, error)
	GetWorkout(ctx context.Context, in *Workout, opts ...grpc.CallOption) (*Workout, error)
	CreateWorkout(ctx context.Context, in *Workout, opts ...grpc.CallOption) (*Workout, error)
	UpdateWorkout(ctx context.Context, in *Workout, opts ...grpc.CallOption) (*Workout, error)
	DeleteWorkout(ctx context.Context, in *Workout, opts ...grpc.CallOption) (*Workout, error)
	// FIGURE INSTANCE ROUTES //
	GetFigureInstance(ctx context.Context, in *FigureInstance, opts ...grpc.CallOption) (*FigureInstance, error)
	UpdateFigureInstance(ctx context.Context, in *FigureInstance, opts ...grpc.CallOption) (*FigureInstance, error)
	CreateFigureInstance(ctx context.Context, in *FigureInstance, opts ...grpc.CallOption) (*FigureInstance, error)
	DeleteFigureInstance(ctx context.Context, in *FigureInstance, opts ...grpc.CallOption) (*FigureInstance, error)
	GetFigureInstances(ctx context.Context, in *User, opts ...grpc.CallOption) (*MultiFigureInstance, error)
	// FIGURE ROUTES //
	GetFigure(ctx context.Context, in *Figure, opts ...grpc.CallOption) (*Figure, error)
	UpdateFigure(ctx context.Context, in *Figure, opts ...grpc.CallOption) (*Figure, error)
	CreateFigure(ctx context.Context, in *Figure, opts ...grpc.CallOption) (*Figure, error)
	DeleteFigure(ctx context.Context, in *Figure, opts ...grpc.CallOption) (*Figure, error)
	GetFigures(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MultiFigure, error)
	// SKIN INSTANCE ROUTES //
	GetSkinInstance(ctx context.Context, in *SkinInstance, opts ...grpc.CallOption) (*SkinInstance, error)
	UpdateSkinInstance(ctx context.Context, in *SkinInstance, opts ...grpc.CallOption) (*SkinInstance, error)
	CreateSkinInstance(ctx context.Context, in *SkinInstance, opts ...grpc.CallOption) (*SkinInstance, error)
	DeleteSkinInstance(ctx context.Context, in *SkinInstance, opts ...grpc.CallOption) (*SkinInstance, error)
	GetSkinInstances(ctx context.Context, in *User, opts ...grpc.CallOption) (*MultiSkinInstance, error)
	// SKIN ROUTES //
	GetSkin(ctx context.Context, in *Skin, opts ...grpc.CallOption) (*Skin, error)
	UpdateSkin(ctx context.Context, in *Skin, opts ...grpc.CallOption) (*Skin, error)
	CreateSkin(ctx context.Context, in *Skin, opts ...grpc.CallOption) (*Skin, error)
	DeleteSkin(ctx context.Context, in *Skin, opts ...grpc.CallOption) (*Skin, error)
}

type routesClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutesClient(cc grpc.ClientConnInterface) RoutesClient {
	return &routesClient{cc}
}

func (c *routesClient) GetUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/routes.Routes/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/routes.Routes/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/routes.Routes/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) DeleteUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/routes.Routes/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) GetWorkouts(ctx context.Context, in *User, opts ...grpc.CallOption) (*MultiWorkout, error) {
	out := new(MultiWorkout)
	err := c.cc.Invoke(ctx, "/routes.Routes/GetWorkouts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) GetWorkout(ctx context.Context, in *Workout, opts ...grpc.CallOption) (*Workout, error) {
	out := new(Workout)
	err := c.cc.Invoke(ctx, "/routes.Routes/GetWorkout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) CreateWorkout(ctx context.Context, in *Workout, opts ...grpc.CallOption) (*Workout, error) {
	out := new(Workout)
	err := c.cc.Invoke(ctx, "/routes.Routes/CreateWorkout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) UpdateWorkout(ctx context.Context, in *Workout, opts ...grpc.CallOption) (*Workout, error) {
	out := new(Workout)
	err := c.cc.Invoke(ctx, "/routes.Routes/UpdateWorkout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) DeleteWorkout(ctx context.Context, in *Workout, opts ...grpc.CallOption) (*Workout, error) {
	out := new(Workout)
	err := c.cc.Invoke(ctx, "/routes.Routes/DeleteWorkout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) GetFigureInstance(ctx context.Context, in *FigureInstance, opts ...grpc.CallOption) (*FigureInstance, error) {
	out := new(FigureInstance)
	err := c.cc.Invoke(ctx, "/routes.Routes/GetFigureInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) UpdateFigureInstance(ctx context.Context, in *FigureInstance, opts ...grpc.CallOption) (*FigureInstance, error) {
	out := new(FigureInstance)
	err := c.cc.Invoke(ctx, "/routes.Routes/UpdateFigureInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) CreateFigureInstance(ctx context.Context, in *FigureInstance, opts ...grpc.CallOption) (*FigureInstance, error) {
	out := new(FigureInstance)
	err := c.cc.Invoke(ctx, "/routes.Routes/CreateFigureInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) DeleteFigureInstance(ctx context.Context, in *FigureInstance, opts ...grpc.CallOption) (*FigureInstance, error) {
	out := new(FigureInstance)
	err := c.cc.Invoke(ctx, "/routes.Routes/DeleteFigureInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) GetFigureInstances(ctx context.Context, in *User, opts ...grpc.CallOption) (*MultiFigureInstance, error) {
	out := new(MultiFigureInstance)
	err := c.cc.Invoke(ctx, "/routes.Routes/GetFigureInstances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) GetFigure(ctx context.Context, in *Figure, opts ...grpc.CallOption) (*Figure, error) {
	out := new(Figure)
	err := c.cc.Invoke(ctx, "/routes.Routes/GetFigure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) UpdateFigure(ctx context.Context, in *Figure, opts ...grpc.CallOption) (*Figure, error) {
	out := new(Figure)
	err := c.cc.Invoke(ctx, "/routes.Routes/UpdateFigure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) CreateFigure(ctx context.Context, in *Figure, opts ...grpc.CallOption) (*Figure, error) {
	out := new(Figure)
	err := c.cc.Invoke(ctx, "/routes.Routes/CreateFigure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) DeleteFigure(ctx context.Context, in *Figure, opts ...grpc.CallOption) (*Figure, error) {
	out := new(Figure)
	err := c.cc.Invoke(ctx, "/routes.Routes/DeleteFigure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) GetFigures(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MultiFigure, error) {
	out := new(MultiFigure)
	err := c.cc.Invoke(ctx, "/routes.Routes/GetFigures", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) GetSkinInstance(ctx context.Context, in *SkinInstance, opts ...grpc.CallOption) (*SkinInstance, error) {
	out := new(SkinInstance)
	err := c.cc.Invoke(ctx, "/routes.Routes/GetSkinInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) UpdateSkinInstance(ctx context.Context, in *SkinInstance, opts ...grpc.CallOption) (*SkinInstance, error) {
	out := new(SkinInstance)
	err := c.cc.Invoke(ctx, "/routes.Routes/UpdateSkinInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) CreateSkinInstance(ctx context.Context, in *SkinInstance, opts ...grpc.CallOption) (*SkinInstance, error) {
	out := new(SkinInstance)
	err := c.cc.Invoke(ctx, "/routes.Routes/CreateSkinInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) DeleteSkinInstance(ctx context.Context, in *SkinInstance, opts ...grpc.CallOption) (*SkinInstance, error) {
	out := new(SkinInstance)
	err := c.cc.Invoke(ctx, "/routes.Routes/DeleteSkinInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) GetSkinInstances(ctx context.Context, in *User, opts ...grpc.CallOption) (*MultiSkinInstance, error) {
	out := new(MultiSkinInstance)
	err := c.cc.Invoke(ctx, "/routes.Routes/GetSkinInstances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) GetSkin(ctx context.Context, in *Skin, opts ...grpc.CallOption) (*Skin, error) {
	out := new(Skin)
	err := c.cc.Invoke(ctx, "/routes.Routes/GetSkin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) UpdateSkin(ctx context.Context, in *Skin, opts ...grpc.CallOption) (*Skin, error) {
	out := new(Skin)
	err := c.cc.Invoke(ctx, "/routes.Routes/UpdateSkin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) CreateSkin(ctx context.Context, in *Skin, opts ...grpc.CallOption) (*Skin, error) {
	out := new(Skin)
	err := c.cc.Invoke(ctx, "/routes.Routes/CreateSkin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routesClient) DeleteSkin(ctx context.Context, in *Skin, opts ...grpc.CallOption) (*Skin, error) {
	out := new(Skin)
	err := c.cc.Invoke(ctx, "/routes.Routes/DeleteSkin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutesServer is the server API for Routes service.
// All implementations must embed UnimplementedRoutesServer
// for forward compatibility
type RoutesServer interface {
	// USER ROUTES //
	GetUser(context.Context, *User) (*User, error)
	CreateUser(context.Context, *User) (*User, error)
	UpdateUser(context.Context, *User) (*User, error)
	DeleteUser(context.Context, *User) (*User, error)
	// WORKOUT ROUTES //
	GetWorkouts(context.Context, *User) (*MultiWorkout, error)
	GetWorkout(context.Context, *Workout) (*Workout, error)
	CreateWorkout(context.Context, *Workout) (*Workout, error)
	UpdateWorkout(context.Context, *Workout) (*Workout, error)
	DeleteWorkout(context.Context, *Workout) (*Workout, error)
	// FIGURE INSTANCE ROUTES //
	GetFigureInstance(context.Context, *FigureInstance) (*FigureInstance, error)
	UpdateFigureInstance(context.Context, *FigureInstance) (*FigureInstance, error)
	CreateFigureInstance(context.Context, *FigureInstance) (*FigureInstance, error)
	DeleteFigureInstance(context.Context, *FigureInstance) (*FigureInstance, error)
	GetFigureInstances(context.Context, *User) (*MultiFigureInstance, error)
	// FIGURE ROUTES //
	GetFigure(context.Context, *Figure) (*Figure, error)
	UpdateFigure(context.Context, *Figure) (*Figure, error)
	CreateFigure(context.Context, *Figure) (*Figure, error)
	DeleteFigure(context.Context, *Figure) (*Figure, error)
	GetFigures(context.Context, *emptypb.Empty) (*MultiFigure, error)
	// SKIN INSTANCE ROUTES //
	GetSkinInstance(context.Context, *SkinInstance) (*SkinInstance, error)
	UpdateSkinInstance(context.Context, *SkinInstance) (*SkinInstance, error)
	CreateSkinInstance(context.Context, *SkinInstance) (*SkinInstance, error)
	DeleteSkinInstance(context.Context, *SkinInstance) (*SkinInstance, error)
	GetSkinInstances(context.Context, *User) (*MultiSkinInstance, error)
	// SKIN ROUTES //
	GetSkin(context.Context, *Skin) (*Skin, error)
	UpdateSkin(context.Context, *Skin) (*Skin, error)
	CreateSkin(context.Context, *Skin) (*Skin, error)
	DeleteSkin(context.Context, *Skin) (*Skin, error)
	mustEmbedUnimplementedRoutesServer()
}

// UnimplementedRoutesServer must be embedded to have forward compatible implementations.
type UnimplementedRoutesServer struct {
}

func (UnimplementedRoutesServer) GetUser(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedRoutesServer) CreateUser(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedRoutesServer) UpdateUser(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedRoutesServer) DeleteUser(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedRoutesServer) GetWorkouts(context.Context, *User) (*MultiWorkout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkouts not implemented")
}
func (UnimplementedRoutesServer) GetWorkout(context.Context, *Workout) (*Workout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkout not implemented")
}
func (UnimplementedRoutesServer) CreateWorkout(context.Context, *Workout) (*Workout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkout not implemented")
}
func (UnimplementedRoutesServer) UpdateWorkout(context.Context, *Workout) (*Workout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWorkout not implemented")
}
func (UnimplementedRoutesServer) DeleteWorkout(context.Context, *Workout) (*Workout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkout not implemented")
}
func (UnimplementedRoutesServer) GetFigureInstance(context.Context, *FigureInstance) (*FigureInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFigureInstance not implemented")
}
func (UnimplementedRoutesServer) UpdateFigureInstance(context.Context, *FigureInstance) (*FigureInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFigureInstance not implemented")
}
func (UnimplementedRoutesServer) CreateFigureInstance(context.Context, *FigureInstance) (*FigureInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFigureInstance not implemented")
}
func (UnimplementedRoutesServer) DeleteFigureInstance(context.Context, *FigureInstance) (*FigureInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFigureInstance not implemented")
}
func (UnimplementedRoutesServer) GetFigureInstances(context.Context, *User) (*MultiFigureInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFigureInstances not implemented")
}
func (UnimplementedRoutesServer) GetFigure(context.Context, *Figure) (*Figure, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFigure not implemented")
}
func (UnimplementedRoutesServer) UpdateFigure(context.Context, *Figure) (*Figure, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFigure not implemented")
}
func (UnimplementedRoutesServer) CreateFigure(context.Context, *Figure) (*Figure, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFigure not implemented")
}
func (UnimplementedRoutesServer) DeleteFigure(context.Context, *Figure) (*Figure, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFigure not implemented")
}
func (UnimplementedRoutesServer) GetFigures(context.Context, *emptypb.Empty) (*MultiFigure, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFigures not implemented")
}
func (UnimplementedRoutesServer) GetSkinInstance(context.Context, *SkinInstance) (*SkinInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSkinInstance not implemented")
}
func (UnimplementedRoutesServer) UpdateSkinInstance(context.Context, *SkinInstance) (*SkinInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSkinInstance not implemented")
}
func (UnimplementedRoutesServer) CreateSkinInstance(context.Context, *SkinInstance) (*SkinInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSkinInstance not implemented")
}
func (UnimplementedRoutesServer) DeleteSkinInstance(context.Context, *SkinInstance) (*SkinInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSkinInstance not implemented")
}
func (UnimplementedRoutesServer) GetSkinInstances(context.Context, *User) (*MultiSkinInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSkinInstances not implemented")
}
func (UnimplementedRoutesServer) GetSkin(context.Context, *Skin) (*Skin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSkin not implemented")
}
func (UnimplementedRoutesServer) UpdateSkin(context.Context, *Skin) (*Skin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSkin not implemented")
}
func (UnimplementedRoutesServer) CreateSkin(context.Context, *Skin) (*Skin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSkin not implemented")
}
func (UnimplementedRoutesServer) DeleteSkin(context.Context, *Skin) (*Skin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSkin not implemented")
}
func (UnimplementedRoutesServer) mustEmbedUnimplementedRoutesServer() {}

// UnsafeRoutesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutesServer will
// result in compilation errors.
type UnsafeRoutesServer interface {
	mustEmbedUnimplementedRoutesServer()
}

func RegisterRoutesServer(s grpc.ServiceRegistrar, srv RoutesServer) {
	s.RegisterService(&Routes_ServiceDesc, srv)
}

func _Routes_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).GetUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).CreateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).UpdateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).DeleteUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_GetWorkouts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).GetWorkouts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/GetWorkouts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).GetWorkouts(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_GetWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Workout)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).GetWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/GetWorkout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).GetWorkout(ctx, req.(*Workout))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_CreateWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Workout)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).CreateWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/CreateWorkout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).CreateWorkout(ctx, req.(*Workout))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_UpdateWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Workout)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).UpdateWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/UpdateWorkout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).UpdateWorkout(ctx, req.(*Workout))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_DeleteWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Workout)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).DeleteWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/DeleteWorkout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).DeleteWorkout(ctx, req.(*Workout))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_GetFigureInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FigureInstance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).GetFigureInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/GetFigureInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).GetFigureInstance(ctx, req.(*FigureInstance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_UpdateFigureInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FigureInstance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).UpdateFigureInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/UpdateFigureInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).UpdateFigureInstance(ctx, req.(*FigureInstance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_CreateFigureInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FigureInstance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).CreateFigureInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/CreateFigureInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).CreateFigureInstance(ctx, req.(*FigureInstance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_DeleteFigureInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FigureInstance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).DeleteFigureInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/DeleteFigureInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).DeleteFigureInstance(ctx, req.(*FigureInstance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_GetFigureInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).GetFigureInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/GetFigureInstances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).GetFigureInstances(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_GetFigure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Figure)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).GetFigure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/GetFigure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).GetFigure(ctx, req.(*Figure))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_UpdateFigure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Figure)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).UpdateFigure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/UpdateFigure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).UpdateFigure(ctx, req.(*Figure))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_CreateFigure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Figure)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).CreateFigure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/CreateFigure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).CreateFigure(ctx, req.(*Figure))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_DeleteFigure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Figure)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).DeleteFigure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/DeleteFigure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).DeleteFigure(ctx, req.(*Figure))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_GetFigures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).GetFigures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/GetFigures",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).GetFigures(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_GetSkinInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkinInstance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).GetSkinInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/GetSkinInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).GetSkinInstance(ctx, req.(*SkinInstance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_UpdateSkinInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkinInstance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).UpdateSkinInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/UpdateSkinInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).UpdateSkinInstance(ctx, req.(*SkinInstance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_CreateSkinInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkinInstance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).CreateSkinInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/CreateSkinInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).CreateSkinInstance(ctx, req.(*SkinInstance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_DeleteSkinInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkinInstance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).DeleteSkinInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/DeleteSkinInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).DeleteSkinInstance(ctx, req.(*SkinInstance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_GetSkinInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).GetSkinInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/GetSkinInstances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).GetSkinInstances(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_GetSkin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Skin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).GetSkin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/GetSkin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).GetSkin(ctx, req.(*Skin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_UpdateSkin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Skin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).UpdateSkin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/UpdateSkin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).UpdateSkin(ctx, req.(*Skin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_CreateSkin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Skin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).CreateSkin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/CreateSkin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).CreateSkin(ctx, req.(*Skin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routes_DeleteSkin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Skin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).DeleteSkin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routes.Routes/DeleteSkin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).DeleteSkin(ctx, req.(*Skin))
	}
	return interceptor(ctx, in, info, handler)
}

// Routes_ServiceDesc is the grpc.ServiceDesc for Routes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Routes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "routes.Routes",
	HandlerType: (*RoutesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _Routes_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _Routes_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Routes_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Routes_DeleteUser_Handler,
		},
		{
			MethodName: "GetWorkouts",
			Handler:    _Routes_GetWorkouts_Handler,
		},
		{
			MethodName: "GetWorkout",
			Handler:    _Routes_GetWorkout_Handler,
		},
		{
			MethodName: "CreateWorkout",
			Handler:    _Routes_CreateWorkout_Handler,
		},
		{
			MethodName: "UpdateWorkout",
			Handler:    _Routes_UpdateWorkout_Handler,
		},
		{
			MethodName: "DeleteWorkout",
			Handler:    _Routes_DeleteWorkout_Handler,
		},
		{
			MethodName: "GetFigureInstance",
			Handler:    _Routes_GetFigureInstance_Handler,
		},
		{
			MethodName: "UpdateFigureInstance",
			Handler:    _Routes_UpdateFigureInstance_Handler,
		},
		{
			MethodName: "CreateFigureInstance",
			Handler:    _Routes_CreateFigureInstance_Handler,
		},
		{
			MethodName: "DeleteFigureInstance",
			Handler:    _Routes_DeleteFigureInstance_Handler,
		},
		{
			MethodName: "GetFigureInstances",
			Handler:    _Routes_GetFigureInstances_Handler,
		},
		{
			MethodName: "GetFigure",
			Handler:    _Routes_GetFigure_Handler,
		},
		{
			MethodName: "UpdateFigure",
			Handler:    _Routes_UpdateFigure_Handler,
		},
		{
			MethodName: "CreateFigure",
			Handler:    _Routes_CreateFigure_Handler,
		},
		{
			MethodName: "DeleteFigure",
			Handler:    _Routes_DeleteFigure_Handler,
		},
		{
			MethodName: "GetFigures",
			Handler:    _Routes_GetFigures_Handler,
		},
		{
			MethodName: "GetSkinInstance",
			Handler:    _Routes_GetSkinInstance_Handler,
		},
		{
			MethodName: "UpdateSkinInstance",
			Handler:    _Routes_UpdateSkinInstance_Handler,
		},
		{
			MethodName: "CreateSkinInstance",
			Handler:    _Routes_CreateSkinInstance_Handler,
		},
		{
			MethodName: "DeleteSkinInstance",
			Handler:    _Routes_DeleteSkinInstance_Handler,
		},
		{
			MethodName: "GetSkinInstances",
			Handler:    _Routes_GetSkinInstances_Handler,
		},
		{
			MethodName: "GetSkin",
			Handler:    _Routes_GetSkin_Handler,
		},
		{
			MethodName: "UpdateSkin",
			Handler:    _Routes_UpdateSkin_Handler,
		},
		{
			MethodName: "CreateSkin",
			Handler:    _Routes_CreateSkin_Handler,
		},
		{
			MethodName: "DeleteSkin",
			Handler:    _Routes_DeleteSkin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "routes.proto",
}
