// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI_5chkouVZZ7A5X-jyWFJl1zbYGl4tcM',
    appId: '1:107506093040:web:3167d4a8ea95e665b66b35',
    messagingSenderId: '107506093040',
    projectId: 'fitness-figure',
    authDomain: 'fitness-figure.firebaseapp.com',
    storageBucket: 'fitness-figure.appspot.com',
    measurementId: 'G-CC2PCQB22X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBWbcpoV7jSxvHfUMrPv0fosfbNuH1ZSc',
    appId: '1:107506093040:android:21361d5f9564a0f1b66b35',
    messagingSenderId: '107506093040',
    projectId: 'fitness-figure',
    storageBucket: 'fitness-figure.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7audmEVMucuE2AebgtLN7uJEw1Ssbqek',
    appId: '1:107506093040:ios:4e82c4b7a71fc303b66b35',
    messagingSenderId: '107506093040',
    projectId: 'fitness-figure',
    storageBucket: 'fitness-figure.appspot.com',
    androidClientId: '107506093040-n41he1kr7f1l6mgbma7oc4do70plmde6.apps.googleusercontent.com',
    iosClientId: '107506093040-t2gqpphhqlj5fn5866hkb7mhnli57kra.apps.googleusercontent.com',
    iosBundleId: 'com.example.ffapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7audmEVMucuE2AebgtLN7uJEw1Ssbqek',
    appId: '1:107506093040:ios:4e82c4b7a71fc303b66b35',
    messagingSenderId: '107506093040',
    projectId: 'fitness-figure',
    storageBucket: 'fitness-figure.appspot.com',
    androidClientId: '107506093040-n41he1kr7f1l6mgbma7oc4do70plmde6.apps.googleusercontent.com',
    iosClientId: '107506093040-t2gqpphhqlj5fn5866hkb7mhnli57kra.apps.googleusercontent.com',
    iosBundleId: 'com.example.ffapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI_5chkouVZZ7A5X-jyWFJl1zbYGl4tcM',
    appId: '1:107506093040:web:6b2e895737236e14b66b35',
    messagingSenderId: '107506093040',
    projectId: 'fitness-figure',
    authDomain: 'fitness-figure.firebaseapp.com',
    storageBucket: 'fitness-figure.appspot.com',
    measurementId: 'G-KYPNX2SE14',
  );

}